* generic settings
Lots of odds and ends here. This is where they end up.
#+begin_src elisp :tangle yes
  (setq idle-update-delay 1.0)
  (add-hook 'focus-out-hook #'garbage-collect)
  (setq-default bidi-display-reordering 'left-to-right
                bidi-paragraph-direction 'left-to-right)
  (setq-default cursor-in-non-selected-windows nil)
  (setq hightlight-nonselected-windows nil)
  (setq x-stretch-cursor t)
  (setq fast-but-imprecise-scrolling t)
  (setq inhibit-compacting-font-caches t)
  (menu-bar-mode 0)
  (add-hook 'org-mode-hook 'visual-line-mode)

  ;; ID basics
  (setq user-full-name "Matthew Lemon"
        user-mail-address "matt@matthewlemon.com")

  ;; UI
  (setq inhibit-startup-message 1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (set-fringe-mode 10)

  (put 'narrow-to-defun  'disabled nil)
  (put 'narrow-to-page   'disabled nil)
  (put 'narrow-to-region 'disabled nil)

  (setq dired-recursive-copies 'always)

  (fset 'yes-or-no-p 'y-or-n-p)

  (global-auto-revert-mode)

  (setq make-backup-files nil          ; don't create backup files
        create-lockfiles nil           ; don't create lockfiles
        auto-save-default nil          ; don't auto-save to #file#
        auto-save-file-name-transforms `((".*" ,temporary-file-directory t))) ; but if auto-save is on, put it in /tmp

  (display-time-mode t)

  (setq visible-bell t)

  (setq display-line-numbers-type `relative)
  (setq undo-limit 8000000) ; raise limit to 80Mb
  (setq truncate-string-ellipsis "…") ; better than using dots
  (setq scroll-preserve-screen-position 'always) ; experimental
  (setq scroll-margin 3) ; bit of space

  ;; calendar proper Monday start
  (setq calendar-week-start-day 1)
  (setq calendar-date-style (quote european))

  ;; Handling tabs (for programming)
  (setq-default tab-width 2)
  (setq-default tab-width 2 indent-tabs-mode nil)
  (setq-default indent-tabs-mode nil)
  (setq js-indent-level 2)
  (setq css-indent-offset 2)
  (add-hook 'sh-mode-hook
            (lambda ()
              (setq sh-basic-offset 2
                    sh-indentation 2)))
  (setq web-mode-markup-indent-offset 2)

  ;; Highlight matching parens
  (show-paren-mode t)

  ;; Stop C-z suspending emacs
  (global-set-key (kbd "C-z") 'nil)

  ;; encoding
  (prefer-coding-system 'utf-8)
  (setq coding-system-for-read 'utf-8)
  (setq coding-system-for-write 'utf-8)

  (global-set-key (kbd "C-x C-l") #'toggle-truncate-lines)
  (global-set-key (kbd "C-+") #'text-scale-increase)
  (global-set-key (kbd "C--") #'text-scale-decrease)
  (global-set-key (kbd "M-n") #'forward-paragraph)
  (global-set-key (kbd "M-p") #'backward-paragraph)

  (setq calendar-latitude 55.77)
  (setq calendar-longitude -2.01)
  (setq calendar-location-name "Berwick-upon-Tweed")
#+end_src

** Some more generic stuff I got from this web site: https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/

*** Disable Bidirectional Text Scanning

If you don’t edit right-to-left languages (Arabic, Hebrew, etc.), Emacs is doing a bunch of work on every redisplay cycle for nothing. These settings tell Emacs to assume left-to-right text everywhere and skip the bidirectional parenthesis algorithm:

#+begin_src elisp :tangle yes
  (setq-default bidi-display-reordering 'left-to-right
                bidi-paragraph-direction 'left-to-right)
  (setq bidi-inhibit-bpa t)
#+end_src

*** Increase Process Output Buffer for LSP

The default read-process-output-max is 64KB, which is still quite conservative. Modern LSP servers like rust-analyzer or clangd routinely send multi-megabyte responses. Bumping this reduces the number of read calls Emacs has to make:

#+begin_src elisp :tangle yes
  (setq read-process-output-max (* 4 1024 1024)) ; 4MB
#+end_src

*** Redisplay fontification on input

Emacs normally fontifies (syntax-highlights) text even while you’re actively typing. This can cause micro-stutters, especially in tree-sitter modes or large buffers. One setting fixes it:

#+begin_src elisp :tangle yes
  (setq redisplay-skip-fontification-on-input t)
#+end_src

*** Don’t Render Cursors in Non-Focused Window

If you have several windows visible, Emacs draws a cursor in each of them – even the ones you’re not working in. It also highlights selections in non-focused windows. Two settings to stop that:

#+begin_src elisp :tangle yes
  (setq-default cursor-in-non-selected-windows nil)
  (setq highlight-nonselected-windows nil)
#+end_src

*** Save the Clipboard Before Killing and No Duplicates in Kill Ring and other kill ring stuff

Allows you to copy from a web site, go back to emacs and kill a line, then you can yank from the kill ring without the thing you copied disappearing:

#+begin_src elisp :tangle yes
  (setq save-interprogram-paste-before-kill t)
  (setq kill-do-not-save-duplicates t)
#+end_src


Most configs that use savehist-mode only persist search rings. But savehist can save any variable – including the kill ring. Add it and you get clipboard history that survives restarts:

#+begin_src elisp :tangle yes
  (setq savehist-additional-variables
      '(search-ring regexp-search-ring kill-ring))
#+end_src

One thing to watch out for: the kill ring can accumulate text properties (fonts, overlays, etc.) that bloat the savehist file. Doom strips them before saving:

#+begin_src elisp :tangle yes
  (add-hook 'savehist-save-hook
            (lambda ()
  			(setq kill-ring
                    (mapcar #'substring-no-properties
                            (cl-remove-if-not #'stringp kill-ring)))))
#+end_src

*** auto-chmod scripts on save

#+begin_src elisp :tangle yes
  (add-hook 'after-save-hook
          #'executable-make-buffer-file-executable-if-script-p)
#+end_src

*** Proportional Window Resizing (Prot)

When you split a window with C-x 2 or C-x 3, Emacs halves the current window. If you already have a multi-window layout, this can produce one awkwardly tiny window while others stay large. With this setting, all windows in the frame resize proportionally:
#+begin_src elisp :tangle yes
  (setq window-combination-resize t)
#+end_src

*** Reversible C-x 1 (Purcell)

C-x 1 (delete-other-windows) is the nuclear option – it nukes your entire window layout to focus on one buffer. Then you spend the next minute recreating the layout you just destroyed.

With winner-mode and a small wrapper, you can make C-x 1 toggle: press it once to go single-window, press it again to restore the previous layout:

#+begin_src elisp :tangle yes
  (winner-mode +1)

  (defun toggle-delete-other-windows ()
    "Delete other windows in frame if any, or restore previous window config."
    (interactive)
    (if (and winner-mode
             (equal (selected-window) (next-window)))
        (winner-undo)
      (delete-other-windows)))

  (global-set-key (kbd "C-x 1") #'toggle-delete-other-windows)  
#+end_src

Just drop this into your config as-is – it’s self-contained. This is one of those tricks where once you have it, you can’t imagine going back.

*** Faster Mark Popping (Purcell, Centaur, Prot)

The mark ring is one of Emacs’s most underused navigation features. Every time you jump somewhere – isearch, M-<, M->, goto-line, imenu, and many more – Emacs pushes your old position onto the mark ring. C-u C-SPC pops it, jumping you back.

The annoyance: you need C-u C-SPC every single time. With this setting, after the first C-u C-SPC you can keep pressing just C-SPC to continue popping:
#+begin_src elisp :tangle yes
  (setq set-mark-command-repeat-pop t)  
#+end_src

This pairs beautifully with repeat-mode if you have it enabled (and you should – see my earlier post on repeat-mode).

*** Recenter After save-place Restores Position (Doom Emacs)

save-place-mode is great – it remembers where you were in each file and jumps back there when you reopen it. The problem is that it can leave your cursor on the last visible line of the window, which is disorienting. This advice recenters the view after the jump:

#+begin_src elisp :tangle yes
  (advice-add 'save-place-find-file-hook :after
              (lambda (&rest _)
                (when buffer-file-name (ignore-errors (recenter)))))
#+end_src

Small thing, but it makes reopening files feel much more natural.

*** Auto-Select Help Windows (Prot)

When you press C-h f or C-h v, Emacs opens the help buffer but leaves your cursor in the original window. You almost always want to read the help right away, so you end up pressing C-x o every single time. This fixes it:

#+begin_src elisp :tangle yes
  (setq help-window-select t)  
#+end_src

* set PATH

We need this for doing stuff in compile buffers, etc

Trying with this new config, using a package to sync the PATH:

#+begin_src elisp :tangle yes
  (use-package exec-path-from-shell
    :ensure t
    :config
    (exec-path-from-shell-initialize))
#+end_src

This was what I previously had. But not sure it worked with fish and it is much more of a hack, by the looks of it:

#+begin_src elisp :tangle yes
  ;; (defun set-exec-path-from-shell-PATH ()
  ;;   "Set up Emacs' `exec-path' and PATH environment variable to match
  ;; that used by the user's shell.

  ;; This is particularly useful under Mac OS X and macOS, where GUI
  ;; apps are not started from a shell."
  ;;   (interactive)
  ;;   (let ((path-from-shell (replace-regexp-in-string
  ;; 			                    "[ \t\n]*$" "" (shell-command-to-string
  ;; 					                                "$SHELL --login -c 'echo $PATH'"))))
  ;;     (setenv "PATH" path-from-shell)
  ;;     (setq exec-path (split-string path-from-shell path-separator))))

  ;; (set-exec-path-from-shell-PATH)
#+end_src

* remove annoying flashing stretched tabs and reset cursor to bar
#+begin_src elisp :tangle yes
  (setq x-stretch-cursor nil)
  (setq-default cursor-type 'box)
#+end_src
* recentf

We like to be able to get recent files, don't we?

#+begin_src elisp :tangle yes
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(setq recentf-max-saved-items 25)
(global-set-key (kbd "C-x C-r") 'recentf-open-files)
#+end_src
* flycheck (disabled in favour of eglot and flymake)
See https://chatgpt.com/c/690268d4-4d1c-832e-9dcf-37950ba372c2 for reasons for the disabling.

#+begin_src elisp :tangle yes
  ;; (use-package flycheck
  ;; :ensure t
  ;; :hook (prog-mode . flycheck-mode)
  ;; :config
  ;; (setq flycheck-global-modes '(not org-mode))
  ;; (flycheck-add-mode 'javascript-eslint 'web-mode)
  ;; (flycheck-add-mode 'javascript-eslint 'js-ts-mode))

  (use-package flycheck
    :ensure t
    :disabled t)

  (use-package flycheck-clj-kondo
    :ensure t
    :disabled t)

    ;; (use-package
    ;; flycheck-clj-kondo
    ;; :hook (after-init . global-flycheck-mode))
#+end_src
* magit
#+begin_src elisp :tangle yes
  (use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))
#+end_src
* vertico

Makes completion in the minibuffer go vertical.

#+begin_src elisp :tangle yes
    (use-package vertico
    :ensure t
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    ;; (vertico-count 20) ;; Show more candidates
    ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))

  (use-package vertico-directory
    :after vertico
    :ensure nil
    :bind (:map vertico-map
                ("RET" . vertico-directory-enter)
                ("DEL" . vertico-directory-delete-char)
                ("M-DEL" . vertico-directory-delete-word))
    :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
#+end_src
* save history

Persist history over Emacs restarts.

#+begin_src elisp :tangle yes
  (use-package savehist
    :init
    (savehist-mode))
#+end_src
* emacs configuration

A lot of this probably comes out of vertico to be honest.

#+begin_src elisp :tangle yes
  (use-package emacs
    :custom
    (context-menu-mode t)
    (completion-cycle-threshold 3) ;; see corfu config
    (tab-always-indent 'complete) ;; see corfu config
    (text-mode-ispell-word-completion nil) ;; see corfu config
    (read-extended-command-predicate #'command-completion-default-include-p)
    (enable-recursive-minibuffers t)
    (read-extended-command-predicate #'command-completion-default-include-p)
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src
* orderless

Maybe we could switch this off - not sure what it does.

#+begin_src elisp :tangle yes
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles partial-completion)))))
#+end_src
* marginalia

Rich annotates in the minibuffer.

#+begin_src elisp :tangle yes
  (use-package marginalia
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))
    :init
    (marginalia-mode))
#+end_src
* ansi colours

Can't really remember why we need this but we do. It might be to prevent bad characters appearing in compilation mode.

#+begin_src elisp :tangle yes
  (use-package ansi-color
    :hook ((compilation-filter . ansi-color-compilation-filter)
           (shell-mode . ansi-color-for-comint-mode)))
  (add-hook 'async-shell-command-after-hook 'ansi-color-for-comint-mode)
#+end_src
* undo-tree

Turn this off if it gets too annoying.

#+begin_src elisp :tangle yes
  (use-package undo-tree
    :config
    (setq undo-tree-auto-save-history nil)
    (setq undo-tree-show-minibuffer-help t)
    (setq undo-tree-minibuffer-help-dynamic t))
#+end_src
* which-key

This is pretty good.

#+begin_src elisp :tangle yes
  (use-package which-key
  :ensure t
  :config
  (which-key-mode))
#+end_src
* multiple cursors

#+begin_src elisp :tangle yes
  (use-package multiple-cursors
  :bind (("C-S-c C-S-c" . mc/edit-lines)
         ("C->" . mc/mark-next-like-this)
         ("C-<" . mc/mark-previous-like-this)
         ("C-c C-<" . mc/mark-all-like-this)
         ("C-\"" . mc/skip-to-next-like-this)
         ("C-:" . mc/skip-to-previous-like-this)))
#+end_src
* dired-x

#+begin_src elisp :tangle yes
  (use-package dired-x
  :ensure nil
  :config
  (setq dired-omit-files
        (concat dired-omit-files "\\|^\\..+$"))
  (setq-default dired-dwim-target t)
  (setq dired-listing-switches "-alh")
  (setq dired-mouse-drag-files t))
#+end_src
* default browser
#+begin_src elisp :tangle yes
  (setq browse-url-browser-function 'eww-browse-url)
#+end_src
* corfu (currently disabled)
#+begin_src elisp :tangle yes
  ;; (use-package corfu
  ;; :ensure t
  ;; ;; Optional customizations
  ;; ;; :custom
  ;; ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  ;; ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
  ;; ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
  ;; ;; (corfu-preview-current nil)    ;; Disable current candidate preview
  ;; ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
  ;; ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches

  ;; ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
  ;; :hook ((prog-mode . corfu-mode)
  ;;        (shell-mode . corfu-mode)
  ;;        (eshell-mode . corfu-mode))
  ;; :init
  ;; ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
  ;; ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
  ;; ;; variable `global-corfu-modes' to exclude certain modes.
  ;; (global-corfu-mode)
  ;; ;; Enable optional extension modes:
  ;; ;; (corfu-history-mode)
  ;; ;; (corfu-popupinfo-mode)
  ;; )
#+end_src
* beacon
#+begin_src elisp :tangle yes
  (use-package beacon
  :ensure t
  :hook (prog-mode . beacon-mode))
#+end_src
* diminish
This is not essential.
#+begin_src elisp :tangle yes
  (use-package diminish
    :config
    (diminish 'completion-preview-mode)
    (diminish 'which-key-mode)
    (diminish 'beacon-mode))
#+end_src
* company
#+begin_src elisp :tangle yes
  ;; For revision see https://chatgpt.com/c/690268d4-4d1c-832e-9dcf-37950ba372c2
  (use-package company
    :ensure t
    :hook (prog-mode . company-mode)
    :config
    (setq company-backends '(company-capf))
    (setq company-idle-delay 0.2
          company-minimum-prefix-length 2
          company-show-numbers t
          company-global-modes '(not org-mode)))

  (with-eval-after-load 'company
    (setq company-backends '(company-capf))
    ;; Optional: TAB triggers completion at point in prog buffers
    (define-key prog-mode-map (kbd "TAB") #'completion-at-point))

  (with-eval-after-load 'completion-preview
    ;; Show the preview already after two symbol characters
    (setq completion-preview-minimum-symbol-length 2)

    ;; Non-standard commands to that should show the preview:

    ;; Org mode has a custom `self-insert-command'
    (push 'org-self-insert-command completion-preview-commands)
    ;; Paredit has a custom `delete-backward-char' command
    (push 'paredit-backward-delete completion-preview-commands)

    ;; Bindings that take effect when the preview is shown:

    ;; Cycle the completion candidate that the preview shows
    (keymap-set completion-preview-active-mode-map "M-n" #'completion-preview-next-candidate)
    (keymap-set completion-preview-active-mode-map "M-p" #'completion-preview-prev-candidate)
    ;; Convenient alternative to C-i after typing one of the above
    )
#+end_src
* ibuffer
#+begin_src elisp :tangle yes
    (use-package ibuffer :ensure nil
    :config
    (setq ibuffer-expert t)
    (setq ibuffer-display-summary nil)
    (setq ibuffer-use-other-window nil)
    (setq ibuffer-show-empty-filter-groups nil)
    (setq ibuffer-default-sorting-mode 'filename/process)
    (setq ibuffer-title-face 'font-lock-doc-face)
    (setq ibuffer-use-header-line t)
    (setq ibuffer-default-shrink-to-minimum-size nil)
    (setq ibuffer-formats
          '((mark modified read-only locked " "
                  (name 30 30 :left :elide)
                  " "
                  (size 9 -1 :right)
                  " "
                  (mode 16 16 :left :elide)
                  " " filename-and-process)
            (mark " "
                  (name 16 -1)
                  " " filename)))
    (setq ibuffer-saved-filter-groups
          '(("Main"
             ("Directories" (mode . dired-mode))
             ("C++" (or
                     (mode . c++-mode)
                     (mode . c++-ts-mode)
                     (mode . c-mode)
                     (mode . c-ts-mode)
                     (mode . c-or-c++-ts-mode)))
             ("Python" (or
                        (mode . python-ts-mode)
                        (mode . c-mode)
                        (mode . python-mode)))
             ("Build" (or
                       (mode . make-mode)
                       (mode . makefile-gmake-mode)
                       (name . "^Makefile$")
                       (mode . change-log-mode)))
             ("Scripts" (or
                         (mode . shell-script-mode)
                         (mode . shell-mode)
                         (mode . sh-mode)
                         (mode . lua-mode)
                         (mode . bat-mode)))
             ("Config" (or
                        (mode . conf-mode)
                        (mode . conf-toml-mode)
                        (mode . toml-ts-mode)
                        (mode . conf-windows-mode)
                        (name . "^\\.clangd$")
                        (name . "^\\.gitignore$")
                        (name . "^Doxyfile$")
                        (name . "^config\\.toml$")
                        (mode . yaml-mode)))
             ("Web" (or
                     (mode . mhtml-mode)
                     (mode . html-mode)
                     (mode . web-mode)
                     (mode . nxml-mode)))
             ("CSS" (or
                     (mode . css-mode)
                     (mode . sass-mode)))
             ("JS" (or
                    (mode . js-mode)
                    (mode . rjsx-mode)))
             ("Markup" (or
                     (mode . markdown-mode)
                     (mode . adoc-mode)))
             ("Org" (mode . org-mode))
             ("LaTeX" (name . "\.tex$"))
             ("Magit" (or
                       (mode . magit-blame-mode)
                       (mode . magit-cherry-mode)
                       (mode . magit-diff-mode)
                       (mode . magit-log-mode)
                       (mode . magit-process-mode)
                       (mode . magit-status-mode)))
             ("Apps" (or
                      (mode . elfeed-search-mode)
                      (mode . elfeed-show-mode)))
             ("Fundamental" (or
                             (mode . fundamental-mode)
                             (mode . text-mode)))
             ("Emacs" (or
                       (mode . emacs-lisp-mode)
                       (name . "^\\*Help\\*$")
                       (name . "^\\*Custom.*")
                       (name . "^\\*Org Agenda\\*$")
                       (name . "^\\*info\\*$")
                       (name . "^\\*scratch\\*$")
                       (name . "^\\*Backtrace\\*$")
                       (name . "^\\*Messages\\*$"))))))
    :hook
    (ibuffer-mode . (lambda ()
                      (ibuffer-switch-to-saved-filter-groups "Main")))
  )
  (global-set-key [(f5)]  #'ibuffer)
#+end_src
* avy (replacement for ace-jump)
#+begin_src elisp :tangle yes
  (use-package avy
    :ensure t
    :bind (("C-'" . avy-goto-char-timer)
  		 ("C-:" . avy-goto-char)
  		 ("M-g f" . avy-goto-line)
  		 ("M-g e" . avy-goto-word-0)))
 #+end_src
* ace-window
#+begin_src elisp :tangle yes
  (use-package ace-window
    :bind (("M-o" . ace-window)))
#+end_src
* provide

#+begin_src elisp :tangle yes
  (provide 'generic)
#+end_src

